Feature/response chatbot issue
ABCall-Project/abcall-websocket-service pull request #10
Opened 2024-10-20 23:34 UTC by fcastagnola92

2024-10-20 23:35 UTC, mvegaruniandes approved these changes

2024-10-21 00:58 UTC, zearkiatos requested changes

2024-10-21 00:58 UTC, zearkiatos commented on config/config.py
> +    URL_ISSUES_SERVICE= os.getenv('URL_ISSUES_SERVICE')
@fcastagnola92 esto deberia quedar mapeado en el config del k8s

2024-10-21 00:58 UTC, zearkiatos commented on websocket.py
> -    if helper.is_empty(message):
@fcastagnola92  esto no debio haberse borrado esto es parte de la validación cuando el mensaje que se envie sea vacio

2024-10-21 01:05 UTC, fcastagnola92 commented on websocket.py
> -    if helper.is_empty(message):
aunque el mensaje esta vacion hay un     return EMPTY_ERROR_RESPONSE por default

2024-10-21 03:43 UTC, zearkiatos approved these changes

2024-10-21 21:52 UTC, merged